# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Model selection - can be overridden with MODEL_TYPE=vggt or MODEL_TYPE=mapanything
MODEL_TYPE ?= mapanything

IMAGE := intel/scenescape-mapping
TEST_IMAGE := intel/scenescape-mapping-test
TARGET = mapping-runtime
TEST_TARGET = mapping-test
USES_SCENE_COMMON := yes
ROOT_DIR := $(abspath ..)
VERSION := $(shell cat ../version.txt)

include ../common.mk

# Override docker build args to include MODEL_TYPE
EXTRA_BUILD_ARGS := --build-arg MODEL_TYPE=$(MODEL_TYPE)

.PHONY: test-build
test-build:
	$(MAKE) IMAGE="$(TEST_IMAGE)" TARGET="$(TEST_TARGET)" MODEL_TYPE=$(MODEL_TYPE)

.PHONY: build-vggt
build-vggt:
	$(MAKE) MODEL_TYPE=vggt IMAGE="intel/scenescape-mapping" VERSION=$(VERSION)-vggt

.PHONY: build-mapanything
build-mapanything:
	$(MAKE) MODEL_TYPE=mapanything IMAGE="intel/scenescape-mapping" VERSION=$(VERSION)-mapanything

.PHONY: build-all
build-all: build-vggt build-mapanything
	docker tag intel/scenescape-mapping:$(VERSION)-mapanything intel/scenescape-mapping:latest
	docker tag intel/scenescape-mapping:$(VERSION)-mapanything intel/scenescape-mapping:$(VERSION)

# Convenience targets
.PHONY: vggt mapanything
vggt: build-vggt
mapanything: build-mapanything

# Override list-dependencies to produce dep files for both MODEL_TYPE modes.
ifndef MAPPING_LIST_DEPS
.PHONY: list-dependencies
list-dependencies: build-vggt build-mapanything
	$(MAKE) MODEL_TYPE=vggt IMAGE=intel/scenescape-mapping VERSION=$(VERSION)-vggt MAPPING_LIST_DEPS=1 list-dependencies
	$(MAKE) MODEL_TYPE=mapanything IMAGE=intel/scenescape-mapping VERSION=$(VERSION)-mapanything MAPPING_LIST_DEPS=1 list-dependencies
endif

# Override generate-sbom to produce SBOMs for both MODEL_TYPE modes.
ifndef MAPPING_GENERATE_SBOM
.PHONY: generate-sbom
generate-sbom: build-vggt build-mapanything
	$(MAKE) ROOT_DIR=$(ROOT_DIR) MODEL_TYPE=vggt IMAGE=intel/scenescape-mapping VERSION=$(VERSION)-vggt MAPPING_GENERATE_SBOM=1 generate-sbom
	$(MAKE) ROOT_DIR=$(ROOT_DIR) MODEL_TYPE=mapanything IMAGE=intel/scenescape-mapping VERSION=$(VERSION)-mapanything MAPPING_GENERATE_SBOM=1 generate-sbom
endif
