# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Intel Corporation

# Build k6 with the xk6-mqtt extension for MQTT load testing.
# xk6 Docker tag 1.4.7 bundles xk6 Go module v1.4.7.
# See: https://github.com/grafana/xk6/releases/tag/v1.4.7
FROM grafana/xk6:1.4.7@sha256:16a4044c63bbef291bd51c9213fdcfaee7342d0fac2c9bb9ec64eca23ac35377 AS builder
ARG http_proxy
ARG https_proxy
ARG no_proxy
RUN xk6 build --with github.com/pmalhaire/xk6-mqtt@v0.40.3

FROM scratch
COPY --from=builder /xk6/k6 /usr/bin/k6
USER 65532:65532
HEALTHCHECK CMD ["/usr/bin/k6", "version"]
ENTRYPOINT ["k6"]
