# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 5.2.15 on 2026-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('manager', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='region',
      name='visible',
      field=models.BooleanField(default=False),
    ),
    migrations.AddField(
      model_name='singletonsensor',
      name='visible',
      field=models.BooleanField(default=False),
    ),
    migrations.AddField(
      model_name='tripwire',
      name='visible',
      field=models.BooleanField(default=False),
    ),
  ]
