# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sscape-gstplugins
data:
  sscape_post_decode_timestamp_capture.py: |
{{ .Files.Get "files/dlsps/sscape_post_decode_timestamp_capture.py" | indent 4 }}
  sscape_post_inference_data_publish.py: |
{{ .Files.Get "files/dlsps/sscape_post_inference_data_publish.py" | indent 4 }}
  sscape_policies.py: |
{{ .Files.Get "files/dlsps/sscape_policies.py" | indent 4 }}
  sscape_3d_detector.py: |
{{ .Files.Get "files/dlsps/sscape_3d_detector.py" | indent 4 }}
  sscape_gst_log.py: |
{{ .Files.Get "files/dlsps/sscape_gst_log.py" | indent 4 }}
